VSCode Marketplace Search Command
SwitchbladeBot/switchblade pull request #1159
Opened 2020-09-04 00:45 UTC by almeidx

Closes #1067

2020-09-04 19:56 UTC, pedrofracassi requested changes

2020-09-04 19:56 UTC, pedrofracassi commented on src/locales/en-US/commands.json
> +    "commandDescription": "Shows information about extensions from the Visual Studio Code Marketplace",
```suggestion
    "commandDescription": "Shows information about VS Code extensions from the Visual Studio Marketplace",
```

2020-09-04 19:56 UTC, pedrofracassi commented on src/locales/en-US/commands.json
> +    "marketplace": "Visual Studio Code Marketplace",
```suggestion
    "marketplace": "Visual Studio Marketplace",
```

2020-09-05 10:48 UTC, fernando457829 approved these changes

2020-09-05 10:50 UTC, fernando457829 commented
LGTM

2020-09-07 21:55 UTC, pedrofracassi submitted a review, later dismissed
LGTM

2020-09-08 15:20 UTC, fernando457829 submitted a review, later dismissed
LGTM ~again~

2020-09-08 19:50 UTC, pedrofracassi approved these changes
LGTM

2020-09-08 19:55 UTC, Tsugami approved these changes

2020-09-11 20:05 UTC, merged