Kanna Paper command
SwitchbladeBot/switchblade pull request #1176
Opened 2020-09-07 20:58 UTC by Tsugami

Closes #692

2020-09-08 23:09 UTC, jaxxibae commented on src/utils/CanvasTemplates.js
> +    console.log(lines)
```suggestion

```

2020-09-08 23:09 UTC, jaxxibae submitted a review, later dismissed
![](https://cdn.discordapp.com/attachments/445647209892020234/753029306837368932/kanna.jpg)

2020-09-08 23:20 UTC, pedrofracassi requested changes

2020-09-08 23:20 UTC, pedrofracassi commented on src/locales/en-US/commands.json
> +    "commandDescription": "Generates a text on the kanna paper.",
```suggestion
    "commandDescription": "Generates an image of Kanna (from Miss Kobayashi's Dragon Maid) holding a paper with text",
```

2020-09-08 23:20 UTC, pedrofracassi commented on src/locales/en-US/commands.json
> +    "missingText": "You have to give me some text for the kanna paper!"
```suggestion
    "missingText": "You have to give me some text for the paper!"
```

2020-09-13 21:01 UTC, pedrofracassi approved these changes
![image](https://user-images.githubusercontent.com/25179120/93028575-25e36280-f5eb-11ea-8804-0e9834186f6c.png)

2020-09-15 21:55 UTC, Doges approved these changes
LGTM




nice

2020-09-15 21:57 UTC, almeidx approved these changes

2020-09-15 22:48 UTC, merged