[WIP] Google Play sub-commands
SwitchbladeBot/switchblade pull request #1191
Opened 2020-09-11 18:27 UTC by Doges

- [x] App
- [x] Developer
- [] Reviews

2020-09-15 21:51 UTC, Doges commented
i wanna die while doing this tbh

2020-09-24 23:48 UTC, Doges commented
RFR

2020-10-02 11:19 UTC, Doges commented
now its rfr

2020-10-04 14:21 UTC, almeidx submitted a review, later dismissed

2020-10-04 14:21 UTC, almeidx commented on src/locales/en-US/commands.json
> +    },
```suggestion
  "rolelist": {
    "commandDescription": "Lists all the roles in the server.",
    "roles": "Roles",
    "ids": "IDs",
    "loading": "Loading roles..."
  },
```

2020-10-04 14:21 UTC, almeidx commented on src/locales/en-US/commands.json
> +    "commandDescription": "Searches for an application, developer or [REDACTED] on Google Play Store",
Redacted?

2020-10-04 14:30 UTC, Doges commented on src/locales/en-US/commands.json
> +    "commandDescription": "Searches for an application, developer or [REDACTED] on Google Play Store",
OH, I FORGOT TO REMOVE

2020-10-04 14:34 UTC, almeidx requested changes
The developer subcommand does not have commandDescription or commandUsage

2020-10-04 14:40 UTC, almeidx submitted a review, later dismissed

2020-10-04 16:25 UTC, jaxxibae submitted a review, later dismissed
Command doesn't error when there's no application/developer.
![](https://cdn.discordapp.com/attachments/445647209892020234/762349494809264148/unknown.png)

2020-10-04 16:25 UTC, jaxxibae commented on src/commands/misc/googleplay/app.js
> +        .setDescription(summary)
```suggestion
        .setDescription(summary.replace(/&amp;/g, '&'))
```

2020-10-04 16:25 UTC, jaxxibae commented on src/commands/misc/googleplay/developer.js
> +        .setDescription(summary)
```suggestion
        .setDescription(summary.replace(/&amp;/g, '&'))
```

2020-10-07 16:57 UTC, Doges commented
> 
> 
> Command doesn't error when there's no application/developer.
> ![](https://camo.githubusercontent.com/bc02b3b5550857d04c07b34b7ba1a029955822b7/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3434353634373230393839323032303233342f3736323334393439343830393236343134382f756e6b6e6f776e2e706e67)

searchcommand should handle that

2020-10-08 15:12 UTC, almeidx approved these changes

2020-10-09 12:39 UTC, Doges commented
alo @SwitchbladeBot/chatbot-core

2020-10-09 16:57 UTC, davipatury approved these changes
LGTM

2020-10-10 02:20 UTC, merged