render hotfix
SwitchbladeBot/switchblade pull request #1195
Opened 2020-09-18 19:55 UTC by moruzerinho6

Now displays author from the message and not from who executed the command.
Fixed attachments being matrix and not an array.

2020-09-19 14:15 UTC, jaxxibae commented
Is it supposed to display the executor's name & avatar? 
![image](https://user-images.githubusercontent.com/32089154/93669258-d7badd00-fa8a-11ea-9c36-2c46dd4dcab3.png)

2020-09-19 19:41 UTC, moruzerinho6 commented
Yes it's, please talk with me about what message you're trying to render in Switchblade's discord.

2020-09-20 15:46 UTC, pedrofracassi commented
Is this RFR?

2020-09-20 17:08 UTC, moruzerinho6 commented
Waiting for @jaxxibae to give me the message that didn't display the author

2020-09-20 17:12 UTC, jaxxibae commented
Ahh yes. https://discordapp.com/channels/445203868624748555/516243264635011072/756607065757057092

2020-09-25 16:59 UTC, almeidx requested changes

2020-09-25 16:59 UTC, almeidx commented on src/commands/utility/render.js
> +        embed.setAuthor(link.author.username, link.author.displayAvatarURL({ dynamic: true }))
```suggestion
          .setAuthor(link.author.username, link.author.displayAvatarURL({ dynamic: true }))
```

2020-09-25 17:09 UTC, almeidx approved these changes

2020-09-26 16:07 UTC, Doges approved these changes
LGTM

2020-09-28 11:10 UTC, merged