removed DiscordUtils#cleanContent
SwitchbladeBot/switchblade pull request #1198
Opened 2020-09-23 17:23 UTC by almeidx

Closes #1172

2020-09-24 00:58 UTC, Doges submitted a review, later dismissed
LGTM

2020-10-01 14:56 UTC, jaxxibae requested changes

2020-10-01 14:56 UTC, jaxxibae commented on src/commands/government/searchplate.js
> +const { Util } = require('discord.js')
```suggestion
const { cleanContent } = require('discord.js').Util
```

2020-10-01 14:56 UTC, jaxxibae commented on src/commands/government/searchplate.js
> +          .setDescription(`**${t('commands:searchplate.plate')}**: ${plate.placa}\n**${t('commands:searchplate.model')}**: ${plate.marca} ${plate.modelo}\n**${t('commands:searchplate.year')}**: ${pla
```suggestion
          .setDescription(`**${t('commands:searchplate.plate')}**: ${plate.placa}\n**${t('commands:searchplate.model')}**: ${plate.marca} ${plate.modelo}\n**${t('commands:searchplate.year')}**: ${plate.anoModelo}\n**${t('commands:searchplate.color')}**: ${plate.cor}\n**${t('commands:searchplate.city')}**: ${plate.municipio} - ${plate.uf}\n**${t('commands:searchplate.status')}**: ${(plate.situacao !== 'Roubo/Furto') ? t('commands:searchplate.notstolen') : `**${t('commands:searchplate.stolen')}**`}\n**${t('commands:searchplate.chassis')}**: ${cleanContent(plate.chassi, message)}\n\n**${t('commands:searchplate.image')}**:`)
```

2020-10-01 14:56 UTC, jaxxibae commented on src/structures/command/parameters/types/StringParameter.js
> +const { Util } = require('discord.js')
```suggestion
const { cleanContent } = require('discord.js').Util
```

2020-10-01 14:56 UTC, jaxxibae commented on src/structures/command/parameters/types/StringParameter.js
> +    if (this.clean) arg = Util.cleanContent(arg, message)
```suggestion
    if (this.clean) arg = cleanContent(arg, message)

```

2020-10-01 14:57 UTC, jaxxibae commented
PS: Test before making changes, because I'm not 100% sure it'll work

2020-10-08 15:08 UTC, Doges approved these changes

2020-10-09 16:57 UTC, davipatury approved these changes
LGTM

2020-10-10 02:30 UTC, merged