Safer math command
SwitchbladeBot/switchblade pull request #1200
Opened 2020-10-01 05:23 UTC by BlueSlimee

The current math command has a serious problem: math operations are executed in the same event loop as the bot. The problem? Heavy math operations (such as `:Infinity` or `:42000000`) will crash the bot. This PR sandboxes all math operations so everything is isolated and safe. Currently, the execution timeout is 10 seconds, but I think it can be brought down to 5 or something.

2020-10-01 12:23 UTC, metehus commented
#895

2020-10-05 14:17 UTC, metehus commented
![image](https://user-images.githubusercontent.com/22124518/95091019-51de9900-06fc-11eb-9872-19700310d497.png)

2020-10-05 14:20 UTC, metehus submitted a review, later dismissed
Sounds smart and good

2020-10-05 14:31 UTC, metehus commented
ok something broke

2020-10-05 14:42 UTC, almeidx requested changes
![](https://i.imgur.com/phdA9A0.png)

2020-10-05 18:37 UTC, almeidx commented on src/commands/utility/math.js
>        this.client.log(`Failed math calculation ${expression}\nError: ${error.stack}`, { tags: [this.name] })
This should be removed imo

2020-10-05 18:37 UTC, almeidx approved these changes
Besides the above, LGTM

2020-10-05 19:37 UTC, almeidx requested changes

2020-10-05 19:37 UTC, almeidx commented on src/commands/utility/math.js
>        this.client.log(`Failed math calculation ${expression}\nError: ${error.stack}`, { tags: [this.name] })
```suggestion
```

2020-10-05 19:42 UTC, almeidx approved these changes
LGTM

2020-10-06 11:56 UTC, Doges approved these changes
LGTM

2020-10-06 12:06 UTC, merged