Added BMI command
SwitchbladeBot/switchblade pull request #1215
Opened 2020-10-01 17:07 UTC by upedd

Closes #875

2020-10-02 12:07 UTC, almeidx commented on src/commands/misc/bmi.js
> +      name: 'bmi',
maybe add a `bobymassindex` alias?

2020-10-02 15:26 UTC, upedd commented
Done

2020-10-02 16:06 UTC, almeidx requested changes

2020-10-02 16:06 UTC, almeidx commented on src/locales/en-US/commands.json
> +    "missingHeight": "You have to specify a valid weight in kilograms.",
```suggestion
    "missingHeight": "You have to specify a valid height in kilograms.",
```

2020-10-02 16:35 UTC, almeidx submitted a review, later dismissed

2020-10-03 12:28 UTC, pedrofracassi submitted a review, later dismissed
LGTM

2020-10-05 13:12 UTC, Doges commented
Please resolve the conflicts.

2021-01-27 15:03 UTC, almeidx approved these changes
LGTM

2021-01-27 15:08 UTC, Doges approved these changes

2021-01-27 15:08 UTC, merged