MessageLinkParameter improvements
SwitchbladeBot/switchblade pull request #1216
Opened 2020-10-01 17:24 UTC by davipatury

2020-10-01 17:28 UTC, davipatury commented on src/structures/command/parameters/types/MessageLinkParameter.js
> -  const Result = []
ALA O CARA USA PASCAL CASE

2020-10-01 17:32 UTC, almeidx requested changes
might as well support the other discord clients

2020-10-01 17:36 UTC, almeidx approved these changes

2020-10-02 11:17 UTC, Doges approved these changes
LGTM

2020-10-02 11:57 UTC, merged