Added Owlbot command
SwitchbladeBot/switchblade pull request #1225
Opened 2020-10-02 16:26 UTC by upedd

closes #1123

2020-10-02 16:26 UTC, upedd commented
![image](https://user-images.githubusercontent.com/56954025/94946699-d226b380-04dc-11eb-8d99-bf20ab7af1f3.png)

2020-10-02 16:34 UTC, almeidx commented
Add the OWLBOT_KEY env variable to the Environment Variables wiki

2020-10-02 16:37 UTC, upedd commented
Where is it?

2020-10-02 16:39 UTC, almeidx commented
> Where is it?

https://github.com/SwitchbladeBot/switchblade/wiki/Environment-Variables

2020-10-02 16:42 UTC, upedd commented
Done

2020-10-02 16:46 UTC, almeidx approved these changes

2020-10-03 12:15 UTC, pedrofracassi requested changes

2020-10-03 12:15 UTC, pedrofracassi commented on src/commands/misc/owlbot.js
> +      if (data.pronunciation) embed.setDescription(data.pronunciation)
Add these two slashes, they're important for written pronunciation :)

![image](https://user-images.githubusercontent.com/25179120/94991323-c678d280-0558-11eb-8e9d-4cb6cf37f2cb.png)

2020-10-03 12:46 UTC, upedd commented
Fixed

2020-10-03 13:35 UTC, almeidx submitted a review, later dismissed

2020-10-04 14:33 UTC, Doges approved these changes
LGTM

2020-10-04 14:34 UTC, Doges approved these changes

2020-10-04 16:29 UTC, jaxxibae approved these changes
LGTM

2020-10-04 16:30 UTC, merged