Genshin Impact commands
SwitchbladeBot/switchblade pull request #1300
Opened 2021-03-28 00:58 UTC by Doges

Closes #1299

2021-04-27 20:06 UTC, almeidx requested changes

2021-04-27 20:06 UTC, almeidx commented on src/commands/games/genshinimpact/characters.js
> +        type: 'string', full: true, missingError: 'commands:freefire.subcommands.weapon.missingWeapon'
freefire?

2021-04-27 20:07 UTC, Doges commented on src/commands/games/genshinimpact/characters.js
> +        type: 'string', full: true, missingError: 'commands:freefire.subcommands.weapon.missingWeapon'
🤫🤫🤫 still wip

2021-09-08 11:06 UTC, Doges commented
Remaking this using @next

2021-09-08 11:06 UTC, closed without merging