Translate phrases to emoji command
SwitchbladeBot/switchblade pull request #1313
Opened 2021-05-16 06:56 UTC by MoPaMo

Based on my [issue#1312](https://github.com/SwitchbladeBot/switchblade/issues/1312), I have now created a command, which takes user input and translates the words into emojis. Right now, the command has a pretty small range of translations, but I think finding new and fun translation is a great thing for PRs.

I've just tested the algorithm itself and haven't run the entire project myself yet, so I'm not sure whether I "registered" my command...

2021-05-16 11:42 UTC, almeidx requested changes

2021-05-16 11:42 UTC, almeidx commented on src/commands/text/emojitr.js
> +const seperators = /([\.,\!\?;])/;
```suggestion
const separators = /([\.,\!\?;])/;
```

2021-05-16 11:42 UTC, almeidx commented on src/commands/text/emojitr.js
> +        word = word.replace(seperators, "");
```suggestion
        let suffix = separators.test(word) ? separators.exec(word)[1] : "";
        word = word.replace(separators, "");
```

2021-05-16 11:43 UTC, almeidx reviewed
I feel like it would be better if you used the emojis directly (😅) instead of keeping the `:emoji_name:` format

2021-05-16 11:46 UTC, almeidx requested changes

2021-05-16 11:46 UTC, almeidx commented on src/commands/text/emojitr.js
> +const separators = /([\.,\!\?;])/;
No need to escape these characters inside a character set
```suggestion
const separators = /([.,!?;])/;
```

2021-05-16 11:47 UTC, MoPaMo commented
> I feel like it would be better if you used the emojis directly (😅) instead of keeping the `:emoji_name:` format

Why? They are converted to emojis by discord and I'm not even sure if the "normal" emojis work…

2021-05-16 11:48 UTC, almeidx commented
> > I feel like it would be better if you used the emojis directly (sweat_smile) instead of keeping the `:emoji_name:` format
> 
> Why? They are converted to emojis by discord and I'm not even sure if the "normal" emojis work…

It would probably make the code easier to read, but it's not a big deal

2021-05-16 11:48 UTC, MoPaMo commented
I  don't know 🤷🏼‍♂️ 😂

2021-05-16 11:55 UTC, almeidx commented
[Github Actions are sort of dying atm](https://www.githubstatus.com/incidents/zbpwygxwb3gw) so the checks aren't running, however, whenever they get back up they are going to fail in this pull request because we do not allow semicolons. 

For the time being, you can run `npm run fix` and `npm run test` locally, which is basically what the github actions would have done if they were working

2021-05-17 17:40 UTC, MoPaMo commented
I fixed the problems[ called out by the linter program](https://github.com/SwitchbladeBot/switchblade/runs/2595080291?check_suite_focus=true), so what do I do now?

2021-05-27 18:57 UTC, MoPaMo commented
I‘m kind of frustrated right now - what did I do wrong so I don’t get any answer? 🙈

2021-05-28 10:15 UTC, Doges commented
> 
> 
> I‘m kind of frustrated right now - what did I do wrong so I don’t get any answer in two weeks? 🙈

nothing, i don't have enough time to test it rn, may take more 4 days for my review

2021-05-28 10:55 UTC, MoPaMo commented
> > I‘m kind of frustrated right now - what did I do wrong so I don’t get any answer in two weeks? 🙈
> 
> nothing, i don't have enough time to test it rn, may take more 4 days for my review

Sorry for being annoying 😅

2021-05-29 16:50 UTC, almeidx requested changes

2021-05-29 16:50 UTC, almeidx commented on src/commands/text/emojitr.js
> +        const suffix = separators.test(word) ? separators.exec(word)[1] : ''
```suggestion
        const suffix = separators.exec(word)?.[1] ?? ''
```

2022-10-13 19:25 UTC, closed without merging