Raffle Command
SwitchbladeBot/switchblade pull request #938
Opened 2019-07-31 17:42 UTC by dpaiv0

+ Closes #880 

![image](https://user-images.githubusercontent.com/32089154/62234580-de881b80-b3c2-11e9-897a-12460d4918f0.png)
![image](https://user-images.githubusercontent.com/32089154/62234591-e2b43900-b3c2-11e9-8d8e-85727c19bfd1.png)
![image](https://user-images.githubusercontent.com/32089154/62234603-eb0c7400-b3c2-11e9-8757-45ee2d2308eb.png)

2019-08-01 00:20 UTC, dpaiv0 commented
> wheres me in the first pic?

You weren't picked by Shieldblade. Dismissing review.

2019-08-01 00:41 UTC, dpaiv0 commented
Don't approve this yet, I didn't see the first print screen. @pedrofracassi is there twice, and that's outrageous.

2020-09-04 03:03 UTC, pedrofracassi commented
Converting this one to a draft.

2020-09-14 13:17 UTC, Doges commented
stale?

2020-10-31 19:31 UTC, Tsugami requested changes

2020-10-31 19:31 UTC, Tsugami commented on src/commands/misc/raffle.js
> +    }
```js
  let raffledUsers = users.filter(m => !m.user.bot).map(u => u.toString())
  const chosen = []

    for (let i = 0; i < amount; i++) {
      const user = raffledUsers[Math.floor(Math.random() * raffledUsers.length)]
      chosen.push(user)
      raffledUsers = raffledUsers.filter(u=> u !== user)
    }
```
solve the problem of duplicate users

2022-10-13 19:25 UTC, closed without merging